In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\final_dataset.csv")

In [4]:
df.shape

(33600, 23)

In [6]:
df.head(1)

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
0,tt0073195,Jaws,https://www.imdb.com/title/tt0073195,1975,2h 4m,PG,8.1,683K,7000000.0,477220580.0,...,"['Peter Benchley', 'Carl Gottlieb']","['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'...",['United States'],"[""Water Street, Edgartown, Martha's Vineyard, ...","['Zanuck/Brown Productions', 'Universal Pictur...",['English'],0,20,0

In [11]:
list(df.Year.unique())
df.Year.unique()

array([1975, 1977, 1966, 1970, 1982, 2020, 2012, 2017, 2011, 2013, 1969,
       1983, 1984, 2019, 2004, 2005, 1961, 2007, 1980, 2024, 1991, 1989,
       1990, 2010, 2002, 1978, 1963, 1967, 1987, 1995, 1962, 2022, 2006,
       1979, 2014, 1974, 1976, 1999, 1998, 1986, 2023, 2009, 1981, 2015,
       2021, 1968, 2016, 2001, 1985, 1996, 1973, 1964, 1965, 1972, 2008,
       2003, 1997, 1960, 1993, 2018, 2000, 1994, 1992, 1971, 1988])

In [12]:
df.isnull().sum()

id                           0
Title                        0
Movie Link                   0
Year                         0
Duration                   221
MPA                       7976
Rating                     138
Votes                      138
budget                   21785
grossWorldWide           15378
gross_US_Canada          16029
opening_weekend_Gross    18077
directors                  359
writers                   1576
stars                      473
genres                     382
countries_origin           366
filming_locations         6729
production_companies      1378
Languages                  474
wins                         0
nominations                  0
oscars                       0
dtype: int64

In [16]:
df = df.ffill()

In [17]:
df.isnull().sum()

id                       0
Title                    0
Movie Link               0
Year                     0
Duration                 0
MPA                      0
Rating                   0
Votes                    0
budget                   0
grossWorldWide           0
gross_US_Canada          0
opening_weekend_Gross    0
directors                0
writers                  0
stars                    0
genres                   0
countries_origin         0
filming_locations        0
production_companies     0
Languages                0
wins                     0
nominations              0
oscars                   0
dtype: int64

In [20]:
df = df[['Year' , 'Duration' , 'MPA' , 'Rating' , 'Votes' ] ]

In [22]:
df

       Year Duration MPA  Rating Votes
0      1975    2h 4m  PG     8.1  683K
1      1975   1h 40m   R     7.4  173K
2      1975   2h 13m   R     8.7  1.1M
3      1975    2h 5m   R     8.0  279K
4      1975   1h 50m   R     6.4   15K
...     ...      ...  ..     ...   ...
33595  1988    2h 7m   R     7.3  1.1K
33596  1988   1h 25m   R     4.9    12
33597  1988   1h 31m  PG     6.8  1.3K
33598  1988   1h 30m  PG     6.3   337
33599  1988   1h 18m  PG     3.1   737

[33600 rows x 5 columns]

In [24]:
df.Rating.mean().round(2)

np.float64(6.16)

In [25]:
df.head(3)

   Year Duration MPA  Rating Votes
0  1975    2h 4m  PG     8.1  683K
1  1975   1h 40m   R     7.4  173K
2  1975   2h 13m   R     8.7  1.1M

In [26]:
# Now we want to find Votes and Duration

In [43]:
li = list(df['Votes'].unique())

In [44]:
li

['683K',
 '173K',
 '1.1M',
 '279K',
 '15K',
 '31K',
 '6.1K',
 '6.7K',
 '23K',
 '65K',
 '1.4K',
 '6.8K',
 '42K',
 '12K',
 '938',
 '22K',
 '596',
 '29K',
 '2.7K',
 '581K',
 '782',
 '27K',
 '4.8K',
 '4.4K',
 '43K',
 '16K',
 '54K',
 '4.9K',
 '7.1K',
 '2.3K',
 '9.3K',
 '68K',
 '189K',
 '2.5K',
 '8.4K',
 '32K',
 '955',
 '5.6K',
 '5.2K',
 '30K',
 '53K',
 '44K',
 '363',
 '24K',
 '19K',
 '20K',
 '767',
 '3.3K',
 '13K',
 '2.8K',
 '34K',
 '2.1K',
 '6.4K',
 '871',
 '10K',
 '2.6K',
 '60K',
 '6.6K',
 '3.4K',
 '3.1K',
 '1.1K',
 '5.7K',
 '3.9K',
 '831',
 '735',
 '1.3K',
 '6K',
 '1.8K',
 '4.6K',
 '7.5K',
 '2.4K',
 '559',
 '3.5K',
 '412',
 '487',
 '544',
 '3.8K',
 '372',
 '774',
 '7K',
 '400',
 '389',
 '1.9K',
 '162',
 '3.2K',
 '607',
 '2.2K',
 '7.7K',
 '1.6K',
 '6.9K',
 '5K',
 '482',
 '7.3K',
 '2K',
 '1.2K',
 '5.3K',
 '236',
 '5.4K',
 '905',
 '903',
 '3K',
 '5.1K',
 '385',
 '201',
 '92',
 '213',
 '837',
 '36',
 '8.2K',
 '398',
 '814',
 '282',
 '294',
 '101',
 '562',
 '313',
 '1.7K',
 '356',
 '736',
 '4K',
 '185',
 '258',
 '431',
 '4.1K',
 '659',
 '75',
 '421',
 '434',
 '944',
 '589',
 '827',
 '81',
 '1.5K',
 '504',
 '4.5K',
 '163',
 '126',
 '685',
 '976',
 '28',
 '520',
 '564',
 '759',
 '789',
 '972',
 '308',
 '314',
 '204',
 '142',
 '787',
 '18',
 '505',
 '418',
 '156',
 '404',
 '183',
 '153',
 '243',
 '37',
 '433',
 '145',
 '255',
 '957',
 '716',
 '134',
 '3.7K',
 '450',
 '348',
 '650',
 '95',
 '1K',
 '423',
 '25K',
 '602',
 '4.2K',
 '902',
 '215',
 '853',
 '256',
 '499',
 '459',
 '61',
 '614',
 '325',
 '720',
 '626',
 '73',
 '977',
 '880',
 '497',
 '492',
 '405',
 '322',
 '898',
 '900',
 '194',
 '188',
 '13',
 '155',
 '415',
 '301',
 '654',
 '566',
 '424',
 '87',
 '171',
 '751',
 '116',
 '677',
 '88',
 '375',
 '369',
 '191',
 '340',
 '233',
 '63',
 '119',
 '525',
 '359',
 '686',
 '212',
 '577',
 '174',
 '493',
 '887',
 '252',
 '428',
 '140',
 '454',
 '553',
 '634',
 '329',
 '107',
 '232',
 '355',
 '419',
 '91',
 '555',
 '19',
 '219',
 '72',
 '643',
 '678',
 '939',
 '263',
 '47',
 '69',
 '66',
 '763',
 '798',
 '220',
 '529',
 '611',
 '448',
 '764',
 '266',
 '49',
 '365',
 '306',
 '775',
 '708',
 '467',
 '350',
 '328',
 '697',
 '983',
 '599',
 '35',
 '197',
 '160',
 '585',
 '169',
 '40',
 '25',
 '311',
 '402',
 '472',
 '76',
 '289',
 '17',
 '638',
 '665',
 '342',
 '352',
 '225',
 '795',
 '135',
 '334',
 '272',
 '576',
 '24',
 '157',
 '321',
 '112',
 '121',
 '182',
 '480',
 '67',
 '605',
 '16',
 '971',
 '303',
 '869',
 '470',
 '370',
 '84',
 '30',
 '540',
 '298',
 '265',
 '109',
 '68',
 '693',
 '65',
 '51',
 '14',
 '516',
 '374',
 '32',
 '34',
 '177',
 '77',
 '148',
 '56',
 '268',
 '228',
 '288',
 '501',
 '461',
 '110',
 '567',
 '79',
 '552',
 '44',
 '442',
 '202',
 '439',
 '1.5M',
 '223K',
 '59K',
 '90K',
 '72K',
 '63K',
 '14K',
 '119K',
 '11K',
 '282K',
 '3.6K',
 '8.3K',
 '26K',
 '8.9K',
 '692',
 '230',
 '36K',
 '18K',
 '110K',
 '894',
 '132K',
 '28K',
 '554',
 '21K',
 '41K',
 '4.3K',
 '7.4K',
 '17K',
 '5.5K',
 '822',
 '111',
 '724',
 '722',
 '859',
 '7.2K',
 '675',
 '765',
 '4.7K',
 '593',
 '595',
 '430',
 '924',
 '89',
 '6.5K',
 '426',
 '8.5K',
 '733',
 '392',
 '862',
 '844',
 '725',
 '948',
 '513',
 '770',
 '218',
 '113',
 '339',
 '698',
 '390',
 '604',
 '672',
 '300',
 '628',
 '866',
 '897',
 '538',
 '386',
 '239',
 '181',
 '857',
 '254',
 '776',
 '641',
 '668',
 '933',
 '59',
 '475',
 '285',
 '323',
 '755',
 '882',
 '807',
 '208',
 '353',
 '884',
 '270',
 '550',
 '368',
 '186',
 '717',
 '646',
 '358',
 '54',
 '195',
 '848',
 '465',
 '703',
 '238',
 '495',
 '958',
 '217',
 '245',
 '778',
 '642',
 '648',
 '281',
 '85',
 '86',
 '136',
 '229',
 '534',
 '852',
 '987',
 '396',
 '364',
 '506',
 '756',
 '793',
 '144',
 '511',
 '427',
 '645',
 '147',
 '128',
 '7.9K',
 '343',
 '97',
 '346',
 '617',
 '149',
 '812',
 '331',
 '64',
 '106',
 '652',
 '874',
 '12',
 '376',
 '251',
 '953',
 '9.4K',
 '658',
 '669',
 '603',
 '673',
 '937',
 '661',
 '387',
 '214',
 '99',
 '512',
 '947',
 '963',
 '354',
 '309',
 '581',
 '332',
 '269',
 '707',
 '104',
 '105',
 '440',
 '168',
 '57',
 '338',
 '38',
 '211',
 '124',
 '83',
 '598',
 '819',
 '951',
 '55',
 '401',
 '490',
 '41',
 '936',
 '291',
 '757',
 '132',
 '622',
 '547',
 '413',
 '27',
 '262',
 '170',
 '227',
 '21',
 '463',
 '277',
 '847',
 '706',
 '393',
 '192',
 '264',
 '94',
 '249',
 '327',
 '705',
 '43',
 '422',
 '320',
 '159',
 '90',
 '82K',
 '837K',
 '69K',
 '58K',
 '575',
 '46K',
 '70K',
 '134K',
 '9.9K',
 '38K',
 '37K',
 '7.8K',
 '5.9K',
 '8K',
 '780',
 '216',
 '843',
 '747',
 '738',
 '210',
 '732',
 '407',
 '235',
 '570',
 '484',
 '999',
 '2.9K',
 '930',
 '502',
 '640',
 '761',
 '873',
 '146',
 '809',
 '742',
 '6.3K',
 '178',
 '838',
 '154',
 '341',
 '473',
 '935',
 '531',
 '510',
 '920',
 '579',
 '785',
 '889',
 '469',
 '452',
 '438',
 '445',
 '98',
 '96',
 '682',
 '5.8K',
 '737',
 '175',
 '500',
 '257',
 '295',
 '568',
 '539',
 '888',
 '446',
 '253',
 '746',
 '636',
 '377',
 '15',
 '791',
 '810',
 '187',
 '478',
 '23',
 '608',
 '662',
 '437',
 '477',
 '926',
 '48',
 '600',
 '205',
 '616',
 '471',
 '699',
 '479',
 '114',
 '666',
 '120',
 '509',
 '143',
 '129',
 '718',
 '31',
 '560',
 '825',
 '962',
 '6',
 '42',
 '986',
 '743',
 '82',
 '173',
 '361',
 '62',
 '449',
 '103',
 '627',
 '528',
 '209',
 '476',
 '489',
 '221',
 '267',
 '237',
 '152',
 '224',
 '458',
 '102',
 '535',
 '8',
 '22',
 '349',
 '443',
 '118',
 '406',
 '80',
 '125',
 '29',
 '78',
 '274',
 '420',
 '409',
 '151',
 '46',
 '324',
 '207',
 '176',
 '448K',
 '117K',
 '64K',
 '217K',
 '131K',
 '88K',
 '186K',
 '51K',
 '48K',
 '242K',
 '284K',
 '74K',
 '166K',
 '843K',
 '87K',
 '55K',
 '488K',
 '8.1K',
 '39K',
 '47K',
 '956',
 '9.7K',
 '863',
 '124K',
 '940',
 '823',
 '447',
 '931',
 '591',
 '916',
 '351',
 '854',
 '40K',
 '9.1K',
 '818',
 '8.8K',
 '858',
 '410',
 '739',
 '783',
 '307',
 '261',
 '290',
 '193',
 '366',
 '674',
 '435',
 '441',
 '921',
 '58',
 '133',
 '745',
 '803',
 '318',
 '9',
 '943',
 '663',
 '8.6K',
 '521',
 '503',
 '242',
 '808',
 '10',
 '275',
 '794',
 '630',
 '50',
 '870',
 '918',
 '486',
 '312',
 '417',
 '592',
 '981',
 '991',
 '635',
 '466',
 '130',
 '558',
 '690',
 '483',
 '71',
 '203',
 '494',
 '750',
 '60',
 '655',
 '571',
 '280',
 '701',
 '373',
 '688',
 '161',
 '728',
 '304',
 '196',
 '910',
 '246',
 '551',
 '523',
 '165',
 '336',
 '637',
 '919',
 '546',
 '545',
 '519',
 '453',
 '380',
 '391',
 '474',
 '536',
 '166',
 '543',
 '187K',
 '296K',
 '171K',
 '271K',
 '73K',
 '266K',
 '176K',
 '56K',
 '617K',
 '80K',
 '298K',
 '61K',
 '94K',
 '81K',
 '101K',
 '97K',
 '66K',
 '76K',
 '71K',
 '77K',
 '220K',
 '139K',
 '190K',
 '102K',
 '206K',
 '150K',
 '398K',
 '49K',
 '9.2K',
 '45',
 '194K',
 '9.8K',
 '141',
 '127',
 '973',
 '629',
 '588',
 '821',
 '180',
 '53',
 '966',
 '691',
 '50K',
 '83K',
 '142K',
 '158K',
 '121K',
 '91K',
 '273K',
 '229K',
 '151K',
 '103K',
 '105K',
 '162K',
 '829',
 '198K',
 '84K',
 '79K',
 '464',
 '62K',
 '100K',
 '33K',
 '45K',
 '9.6K',
 '872',
 '287',
 '715',
 '35K',
 '136K',
 '868',
 '127K',
 '7.6K',
 '656',
 '942',
 '310',
 '6.2K',
 '639',
 '9K',
 '517',
 '1.9M',
 '1M',
 '744K',
 '893K',
 '269K',
 '722K',
 '455K',
 '674K',
 '204K',
 '135K',
 '472K',
 '277K',
 '396K',
 '1.8M',
 '231K',
 '307K',
 '352K',
 '292K',
 '328K',
 '615K',
 '648K',
 '754K',
 '670K',
 '208K',
 '679K',
 '149K',
 '320K',
 '115K',
 '199K',
 '326K',
 '383K',
 '327K',
 '375K',
 '286K',
 '291K',
 '154K',
 '613K',
 '261K',
 '337K',
 '92K',
 '268K',
 '163K',
 '116K',
 '346K',
 '270K',
 '227K',
 '113K',
 '196K',
 '241K',
 '294K',
 '371K',
 '153K',
 '276K',
 '164K',
 '257K',
 '52K',
 '379K',
 '192K',
 '120K',
 '252K',
 '160K',
 '563K',
 '89K',
 '156K',
 '301K',
 '109K',
 '86K',
 '107K',
 '683',
 '380K',
 '335',
 '915',
 '805',
 '292',
 '302',
 '700',
 '964',
 '190',
 '989',
 '75K',
 '200',
 '93K',
 '131',
 '615',
 '885',
 '578',
 '273',
 '260',
 '337',
 '26',
 '117',
 '631',
 '9.5K',
 '333',
 '835',
 '158',
 '687K',
 '342K',
 '713K',
 '469K',
 '782K',
 '743K',
 '632K',
 '841K',
 '165K',
 '487K',
 '874K',
 '631K',
 '762K',
 '742K',
 '179K',
 '147K',
 '325K',
 '359K',
 '311K',
 '185K',
 '175K',
 '637K',
 '306K',
 '378K',
 '697K',
 '530K',
 '67K',
 '212K',
 '253K',
 '456K',
 '172K',
 ...]

In [45]:
df['Votes']

0        683K
1        173K
2        1.1M
3        279K
4         15K
         ...
33595    1.1K
33596      12
33597    1.3K
33598     337
33599     737
Name: Votes, Length: 33600, dtype: str

In [94]:
def convertVotes(val):
    val = str(val)
    if val[-1]=='K':
        return int(float(val[0:len(val)-1])*1000)
    elif val[-1]=='M':
        return int(float(val[0:len(val)-1])*1000000)
    else:
        return int(val)

In [95]:
# 24K ,  23.4K , 2M , 2.5M , 344
convertVotes(232)

232

In [97]:
df.Votes = df.Votes.map(convertVotes)

In [98]:
df.head(3)

   Year Duration MPA  Rating    Votes
0  1975    2h 4m  PG     8.1   683000
1  1975   1h 40m   R     7.4   173000
2  1975   2h 13m   R     8.7  1100000

In [99]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 33600 entries, 0 to 33599
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Year      33600 non-null  int64
 1   Duration  33600 non-null  str
 2   MPA       33600 non-null  str
 3   Rating    33600 non-null  float64
 4   Votes     33600 non-null  int64
dtypes: float64(1), int64(2), str(2)
memory usage: 1.3 MB

In [100]:
df.Votes.mean()

np.float64(30045.64994047619)

In [103]:
df.describe()

               Year        Rating         Votes
count  33600.000000  33600.000000  3.360000e+04
mean    1992.393631      6.155057  3.004565e+04
std       18.957395      1.145707  1.086510e+05
min     1960.000000      1.100000  6.000000e+00
25%     1976.000000      5.500000  5.130000e+02
50%     1993.000000      6.300000  2.200000e+03
75%     2009.000000      7.000000  1.200000e+04
max     2024.000000      9.600000  3.000000e+06

In [105]:
df.Duration.unique()

<StringArray>
[  '2h 4m',  '1h 40m',  '2h 13m',   '2h 5m',  '1h 50m',  '1h 53m',  '2h 16m',
  '1h 51m',  '1h 57m',  '1h 58m',
 ...
  '3h 28m',  '4h 14m',  '4h 18m',       'X',  '5h 25m',   'TV-14',  '5h 45m',
  '7h 19m', '12h 56m',  '3h 23m']
Length: 230, dtype: str

In [106]:
list(df.Duration.unique())

['2h 4m',
 '1h 40m',
 '2h 13m',
 '2h 5m',
 '1h 50m',
 '1h 53m',
 '2h 16m',
 '1h 51m',
 '1h 57m',
 '1h 58m',
 '1h 47m',
 '1h 25m',
 '1h 37m',
 '2h 1m',
 '2h 9m',
 '1h 59m',
 '1h 44m',
 '2h 40m',
 '1h 39m',
 '1h 31m',
 '1h 46m',
 '2h 6m',
 '1h 24m',
 '1h 55m',
 '1h 35m',
 '1h 49m',
 '1h 56m',
 '1h 48m',
 '1h 36m',
 '3h 5m',
 '1h 20m',
 '1h 29m',
 '1h 38m',
 '1h 28m',
 '2h 7m',
 '3h 22m',
 '1h 30m',
 '1h 27m',
 '1h 33m',
 '2h 22m',
 '1h 45m',
 '2h 42m',
 '2h 24m',
 '2h 20m',
 '1h 23m',
 '2h 54m',
 '1h 52m',
 '1h 42m',
 '2h',
 '2h 2m',
 '1h 34m',
 '1h 32m',
 '1h 15m',
 '2h 12m',
 '1h 43m',
 '2h 32m',
 '1h 41m',
 '1h 14m',
 '1h 26m',
 '2h 26m',
 '2h 15m',
 '2h 30m',
 '2h 10m',
 '1h 22m',
 '1h 16m',
 '1h 21m',
 '1h 13m',
 '53m',
 '1h 19m',
 '3h 50m',
 '2h 38m',
 '2h 25m',
 '2h 43m',
 '2h 50m',
 '2h 36m',
 '1h 1m',
 '1h 18m',
 '2h 39m',
 '2h 19m',
 '1h 7m',
 '2h 11m',
 '1h 54m',
 '1h 17m',
 '1h 9m',
 '2h 3m',
 '2h 33m',
 '2h 57m',
 '1h 3m',
 '2h 35m',
 '2h 23m',
 '1h 12m',
 '2h 18m',
 '2h 55m',
 '2h 8m',
 '2h 45m',
 '4h',
 '2h 17m',
 '1h 10m',
 '3h 4m',
 '1h 11m',
 '1h 6m',
 '1h 8m',
 '2h 49m',
 '2h 41m',
 '7h 22m',
 '1h 5m',
 '1h 2m',
 '2h 29m',
 '56m',
 '3h',
 '2h 46m',
 '3h 53m',
 '2h 48m',
 '3h 2m',
 '2h 21m',
 '3h 30m',
 '2h 58m',
 '3h 9m',
 '2h 14m',
 '2h 56m',
 '59m',
 '2h 53m',
 '1h',
 '48m',
 '2h 52m',
 '2h 28m',
 '55m',
 '50m',
 '2h 44m',
 '2h 34m',
 '47m',
 '2h 27m',
 '2h 51m',
 '3h 11m',
 '3h 8m',
 '3h 3m',
 '3h 40m',
 '3h 14m',
 '4h 15m',
 '2h 31m',
 '57m',
 '45m',
 '52m',
 '2h 37m',
 '2h 47m',
 '3h 58m',
 '3h 17m',
 '4h 11m',
 '3h 52m',
 '4h 12m',
 '3h 36m',
 '1h 4m',
 '3h 13m',
 '3h 1m',
 '3h 18m',
 '2h 59m',
 '3h 49m',
 '3h 7m',
 '49m',
 '51m',
 '4h 30m',
 '3h 12m',
 '3h 6m',
 '3h 10m',
 '54m',
 '46m',
 'PG-13',
 '3h 39m',
 '3h 33m',
 '3h 15m',
 '58m',
 '3h 21m',
 '3h 35m',
 '4h 47m',
 '3h 57m',
 '43m',
 '3h 34m',
 '5h 35m',
 '3h 19m',
 '5h 10m',
 '3h 55m',
 '4h 20m',
 '5h 20m',
 '25h',
 '5h 57m',
 '87h',
 '40m',
 '3h 47m',
 '3h 25m',
 '3h 27m',
 '3h 16m',
 '3h 20m',
 '3h 41m',
 '3h 44m',
 '48h',
 '5h 19m',
 '4h 6m',
 '5h 17m',
 '4h 4m',
 '4h 10m',
 '3h 26m',
 '3h 24m',
 'PG',
 '5h 16m',
 '5h 23m',
 '4h 48m',
 '3h 37m',
 '4h 2m',
 '44m',
 '4h 44m',
 '9h 26m',
 '3h 59m',
 '8h 5m',
 '5h 21m',
 '6h 33m',
 '3h 54m',
 '4h 7m',
 '6h 38m',
 '6h 14m',
 'TV-G',
 '3h 28m',
 '4h 14m',
 '4h 18m',
 'X',
 '5h 25m',
 'TV-14',
 '5h 45m',
 '7h 19m',
 '12h 56m',
 '3h 23m']

In [107]:
# 2h 33m , 34m , 1h , error , 87h

In [150]:
def convertDuration(val):
    if len(val.split())==2:
        val = val.split()
        return int(val[0][0:len(val[0])-1])*60 + int(val[1][0:len(val[1])-1])
    elif val[-1] =='h':
        return int(val[0:len(val)-1])*60
    elif val[-1] == 'm':
        return int(val[0:len(val)-1])
    else:
        return convertDuration(df.Duration.mode()[0]) # replacing with mode value {df.Duration.mode()} ==> 1h 30m ==> 90

In [151]:
convertDuration('3213413')

90

In [146]:
df.Duration.mode()

0    1h 30m
Name: Duration, dtype: str

In [152]:
df.Duration  = df.Duration.map(convertDuration)

In [153]:
df.head(1)

   Year  Duration MPA  Rating   Votes
0  1975       124  PG     8.1  683000

In [154]:
df = df.rename(columns= {'Duration' : 'Duration(m)'})

In [155]:
df.head(1)

   Year  Duration(m) MPA  Rating   Votes
0  1975          124  PG     8.1  683000

In [156]:
df['Duration(m)'].mean()

np.float64(103.09723214285714)